services:
  websocket:
    build: .
    env_file: .env.docker
    ports:
      - "8765:8765"
    volumes:
      - ${DATA_HOST_PATH:-../retreival_kite/data/data}:/data
    restart: unless-stopped
    networks:
      - retreival_kite_app-network

networks:
  retreival_kite_app-network:
    external: true
